project:
  type: website

website:
  title: "website"
  navbar:
    right:
      - about.qmd
      - CV/cv.qmd
      - icon: github
        href: https://github.com/
format:
  html:
    theme: [litera, litera-custom.scss]
    mainfont: Inter, sans-serif;
